// Generated by https://github.com/shlomif/fc-solve/blob/master/fc-solve/source/scripts/gen-c-lookup-files.pl
//DO NOT MODIFY DIRECTLY!
pub const OFFSET_BY_I: [usize;52] = [0,21,42,63,84,102,120,138,3,24,45,66,87,105,123,141,6,27,48,69,90,108,126,144,9,30,51,72,93,111,129,147,12,33,54,75,96,114,132,150,15,36,57,78,99,117,135,153,18,39,60,81];
